"""
services/crypto_service.py
--------------------------
Fernet symmetric encryption for secret values at rest.

Fernet = AES-128-CBC + HMAC-SHA256 with a random IV per message.
The key is loaded ONCE from the ENCRYPTION_KEY environment variable.

Security contract
-----------------
  - Plaintext values are passed in as strings and returned as strings.
  - The ciphertext stored on disk is a base64-encoded bytes string.
  - The key is NEVER logged, returned in responses, or written to disk.
  - If ENCRYPTION_KEY is missing at startup, every call raises immediately.
"""

import os
from cryptography.fernet import Fernet, InvalidToken


def _get_fernet() -> Fernet:
    """
    Build a Fernet instance from the environment key.
    Called on every encrypt/decrypt so key rotation only requires
    restarting the process with a new ENCRYPTION_KEY.
    Raises EnvironmentError if the key is missing.
    Raises ValueError if the key is malformed.
    """
    key = os.environ.get("ENCRYPTION_KEY", "")
    if not key:
        raise EnvironmentError(
            "ENCRYPTION_KEY is not set. "
            "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
        )
    try:
        return Fernet(key.encode())
    except Exception:
        raise ValueError(
            "ENCRYPTION_KEY is invalid. "
            "It must be a 32-byte URL-safe base64 string generated by Fernet.generate_key()."
        )


def encrypt(plaintext: str) -> str:
    """
    Encrypt a UTF-8 plaintext string.
    Returns a base64 ciphertext string safe to store in a JSON file.
    Each call produces a different ciphertext (random IV per message).
    """
    f = _get_fernet()
    ciphertext_bytes = f.encrypt(plaintext.encode("utf-8"))
    return ciphertext_bytes.decode("utf-8")


def decrypt(ciphertext: str) -> str:
    """
    Decrypt a base64 ciphertext string produced by encrypt().
    Returns the original plaintext string.
    Raises InvalidToken if tampered, corrupted, or wrong key.
    """
    f = _get_fernet()
    try:
        plaintext_bytes = f.decrypt(ciphertext.encode("utf-8"))
    except InvalidToken:
        raise InvalidToken(
            "Decryption failed. The ciphertext may be corrupted or "
            "the ENCRYPTION_KEY may have changed since this secret was stored."
        )
    return plaintext_bytes.decode("utf-8")